### ISSUE TITLE
readlink using file instead of ls - saves on opening up /etc/passwd and /etc/zoneinfo

### ISSUE THREAD

**Issue by pagerc** [ko1nksm/readlinkf#1]
```
readlink() {
    for DIR ; do
        if [ -L "${DIR}" ] ; then
            LINK=$(file "${DIR}")
            DIR=${LINK#$DIR: *symbolic link to }
        fi
        printf '%s' "$DIR"
    done
}
```

**Comment by ko1nksm** [comment]
Hi,

I think it can be implemented using the `file` command. However, it is not installed / implemented in some environments, despite being specified by POSIX. (e.g. debian docker image, busybox, etc.)

I emphasize portability and reliability.

**Comment by pagerc** [comment]
[Toybox](http://landley.net/toybox/about.html) provides an MIT licensed POSIX compatible alternative to busybox. In the situation where that isn't available, the `fileutils` package can be added to most distributions trivially. As you indicate, the `ls` solution has superior portability to POSIX-like environments such as containers/chroots/phones/routers with only busybox installed.

I'll caveat that it's trivial to identify `file`'s availability:
```
type file >/dev/null 2&1 && {
  .. stuff that depends on file existing
}
```

**Comment by ko1nksm** [comment]
This is not an issue with the `readlinkf` implementation in this repository, so I close it.
